Repository: plone.resource


Branch: refs/heads/1.x
Date: 2018-01-17T19:04:27+01:00
Author: Maurits van Rees (mauritsvanrees) <maurits@vanrees.org>
Commit: https://github.com/plone/plone.resource/commit/dbb0416eec2688e20918041cb75fb6f7728d9c79

Fixed duplicate test name overriding earlier test.

Files changed:
M CHANGES.rst
M plone/resource/tests/test_directory.py

diff --git a/CHANGES.rst b/CHANGES.rst
index b7b5fbe..6d0224b 100644
--- a/CHANGES.rst
+++ b/CHANGES.rst
@@ -14,7 +14,7 @@ New features:
 
 Bug fixes:
 
-- *add item here*
+- Fixed duplicate test name overriding earlier test.  [maurits]
 
 
 1.2.2 (2018-01-17)
diff --git a/plone/resource/tests/test_directory.py b/plone/resource/tests/test_directory.py
index 9e9c4c1..5c5c3f7 100644
--- a/plone/resource/tests/test_directory.py
+++ b/plone/resource/tests/test_directory.py
@@ -229,12 +229,12 @@ def _makeOne(self, name=None):
         path = os.path.join(os.path.dirname(__file__), 'resources')
         return FilesystemResourceDirectory(path, name=name)
 
-    def test_repr(self):
+    def test_repr_default(self):
         dir = self._makeOne()
         s = '<FilesystemResourceDirectory object at resources>'
         self.assertEqual(s, repr(dir))
 
-    def test_repr(self):
+    def test_repr_other_name(self):
         dir = self._makeOne(name='something-else')
         s = '<FilesystemResourceDirectory object at something-else>'
         # This used to give a ValueError: substring not found


